version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
      - ./client/build:/app/client-build
    ports:
      - '3001:3001'
    depends_on:
      - postgres

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app
      - ./uploads:/app/uploads
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  postgres_data: